name: tmdb_api
description: Dart client-side API package for TMDB.org API (https://www.themoviedb.org/).
version: 1.0.0-beta.1
# author: Ratakondala Arun<arunratakondala3470@gmail.com>
homepage: https://github.com/Arunnaidu3470/tmdb_api

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4

dev_dependencies:
  test: ^1.14.2
