name: tmdb_api
description: Dart client-side API package for TMDB.org API (https://www.themoviedb.org/).
version: 2.0.0
# author: Ratakondala Arun<ratakondalaarun@gmail.com>
homepage: https://github.com/RatakondalaArun/tmdb_api.git
issue_tracker: https://github.com/RatakondalaArun/tmdb_api/issues

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  colorize: ^3.0.0
  dio: ^4.0.4

dev_dependencies:
  lint: ^1.8.2
  test: ^1.20.1
