name: Dart Code Analysis

on: [push, pull_request]

jobs:
  package-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: axel-op/dart-package-analyzer@v3
