name: Run Tests CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: pub get
      
    - name: Set Env variables and Run Tests
      env:
        API_V3: ${{ secrets.API_KEY_V3 }}
        API_V4: ${{ secrets.API_KEY_V4 }}
      run: pub run test test/versions/v3/category/
      
